[package]
name = "rust-by-example"
version = "0.1.0"
edition = "2024"

[dependencies]

# BEGIN GENERATED BINS

[[bin]]
name = "remove_push"
path = "src/bin/cli/remove_push.rs"

[[bin]]
name = "error1"
path = "src/bin/error_handling/error1.rs"

[[bin]]
name = "generics1"
path = "src/bin/generics/generics1.rs"

[[bin]]
name = "hashmap1"
path = "src/bin/hashmaps/hashmap1.rs"

[[bin]]
name = "hashmap3"
path = "src/bin/hashmaps/hashmap3.rs"

[[bin]]
name = "hashmap4"
path = "src/bin/hashmaps/hashmap4.rs"

[[bin]]
name = "hashmaps2"
path = "src/bin/hashmaps/hashmaps2.rs"

[[bin]]
name = "if_let1"
path = "src/bin/pattern_matching/if_let1.rs"

[[bin]]
name = "if_let2"
path = "src/bin/pattern_matching/if_let2.rs"

[[bin]]
name = "if_let3"
path = "src/bin/pattern_matching/if_let3.rs"

[[bin]]
name = "match1"
path = "src/bin/pattern_matching/match1.rs"

[[bin]]
name = "match2"
path = "src/bin/pattern_matching/match2.rs"

[[bin]]
name = "match3"
path = "src/bin/pattern_matching/match3.rs"

[[bin]]
name = "match5"
path = "src/bin/pattern_matching/match5.rs"

[[bin]]
name = "shadowing"
path = "src/bin/pattern_matching/shadowing.rs"

[[bin]]
name = "match_pattern1"
path = "src/bin/patterns/match_pattern1.rs"

[[bin]]
name = "patterns1"
path = "src/bin/patterns/patterns1.rs"

[[bin]]
name = "patterns2"
path = "src/bin/patterns/patterns2.rs"

[[bin]]
name = "patterns3"
path = "src/bin/patterns/patterns3.rs"

[[bin]]
name = "patterns4"
path = "src/bin/patterns/patterns4.rs"

[[bin]]
name = "rc1"
path = "src/bin/reference_counter/rc1.rs"

[[bin]]
name = "structs1"
path = "src/bin/structs/structs1.rs"

# END GENERATED BINS
